// CI/CD pipelines with GitHub Actions
// Workflows are process flows that you can set up in your repository to run automated tasks 

// deployment pipeline workflow
name: Deployment pipeline

// The events that trigger the workflow to be executed
on:
  push:
    branches: 
      - master

// jobs will be run in parallel 
jobs:
  deployment_pipeline:
    // setting up the environment that will run this job
    runs-on: ubuntu-20.04

    // steps in each job will be executed sequentially
    steps:
      - name: Checkout repository
        // uses tells workflow to run a specific action - this will checkouts the project source code from git
        uses: actions/checkout@v2

      - name: Setup Node
        // use node to run our code
        uses: actions/setup-node@v1
        // with used to give a "parameter" to the action.
        with:
          node-version: '15.x'

      // install the dependencies of the application
      - name: Install dependencies
        run : npm install

      // lint the code
      - name: Lint
        run: npm run lint